export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

export const ADD_ITEM_IN_CART = 'ADD_ITEM_IN_CART';
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART';
export const DELETE_All_ITEMS = 'DELETE_All_ITEMS';

export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';

export const CURRENT_USER_ADD = 'CURRENT_USER_ADD';
export const CURRENT_USER_DELETE = 'CURRENT_USER_DELETE';