export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const ADD_ITEM_IN_CART = 'ADD_ITEM_IN_CART';
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART';
